### PR TITLE
Security: update expadmin.php

### PR DESCRIPTION
**Pull request by aleiveira**
Added missing **urlencode** function to prevent cross-site scripting (XSS) executed on browsers with no XSS Auditor, such Firefox.

### CODE REVIEW

**Comment by bgreiner** [comment]
Hi Allessandro, 

Could you please submit this pull request to orsee:develop (rather than orsee:master). Our github policy is to merge all bugfixes and features to orsee:develop, from which then new ORSEE versions are created on orsee:master.

Thanks!

/ben

**Comment by kabalin** [comment]
Looks like the branch contains stray merge commits under hashes not matching those on develop branch. @aleiveira any chance you can do a clean clone of develop branch, then cherry-pick 
3919af7 on top and use it in this PR. Thanks!

**Comment by bgreiner** [comment]
Mmmh. Ruslan: If Alessandro does not respond or does not have any capacities to rebase this on current "develop", how do we proceed. Should I just replicate the fix in a new commit and submit as a pull request?

**Comment by kabalin** [comment]
@bgreiner it just needs to be cherry-picked to the clean branch created from the latest state of `develop`. Just for your info, steps I did:
```
> git remote add aleiveira git@github.com:aleiveira/orsee.git
> git fetch aleiveira 
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 4 (delta 3), reused 3 (delta 3), pack-reused 1
Unpacking objects: 100% (4/4), done.
From github.com:aleiveira/orsee
 * [new branch]      ORSEE_20   -> aleiveira/ORSEE_20
 * [new branch]      ORSEE_22   -> aleiveira/ORSEE_22
 * [new branch]      ORSEE_30   -> aleiveira/ORSEE_30
 * [new branch]      develop    -> aleiveira/develop
 * [new branch]      master     -> aleiveira/master
 * [new branch]      patch-1    -> aleiveira/patch-1
> git log -2  aleiveira/patch-1
commit 3919af76d45b57a4a861489f95c824d7e3109eba (aleiveira/patch-1)
Author: aleiveira <...@gmail.com>
Date:   Sat Jul 20 18:20:37 2019 +0100

    Update expadmin.php
    
    Added missing urlencode function to prevent cross-site scripting (XSS).

commit 3d70bbc3e9713296c260f60e1d8369e1a341ec83 (tag: orsee_3.0.5, origin/master, bgreiner/master, aleiveira/master, master)
Merge: 18bf8ab 354445e
Author: Ben Greiner <bgreiner@users.noreply.github.com>
Date:   Tue Nov 28 00:01:27 2017 +0100

    Merge branch 'develop' for Release 3.0.5
> git checkout -b expadmin_urlencode_fix origin/develop
Branch 'expadmin_urlencode_fix' set up to track remote branch 'develop' from 'origin'.
Switched to a new branch 'expadmin_urlencode_fix'
> git cherry-pick 3919af76d45b57a4a861489f95c824d7e3109eba
[expadmin_urlencode_fix 5e1da17] Update expadmin.php
 Author: aleiveira <....@gmail.com>
 Date: Sat Jul 20 18:20:37 2019 +0100
 1 file changed, 1 insertion(+), 1 deletion(-)
> git commit --amend
> git push kabalin expadmin_urlencode_fix
...
```

**Pull request closed without merging**
