### PR TITLE
Fix wrong encoding of umlauts.

### PR DESCRIPTION
**Pull request by MaxG87**
All umlauts appeared in a weired and faulty manner. This change fixes
that.

The change was conducted automatically by issuing the following sed
commands on install/install.sql:

    s/Ã¤/ä/g
    s/Ã¼/ü/g
    s/Ã¶/ö/g
    s/Ãœ/Ü/g
    s/Ã–/Ö/g
    s/Â€//g

### CODE REVIEW

**Comment by kabalin** [comment]
OK, it seems the change diff is not shown because it is a replacement of large chunk of data in the single line. I will leave it for @bgreiner to checkout pull request locally and review.

@MaxG87, one thing I did not mention earlier is commit title - it should have "Bigfix:" prefix (see commit history). But please wait for @bgreiner review before updating the branch with the title amendment, as there might be something else to change.

**Comment by bgreiner** [comment]
Hi Max and Ruslan,

I looked into this, and it is a little bit more complicated than simply fixing the install.sql. For example, the fixed sql file will *not* work for my server and many others.

MySQL apparently has some trouble to consistently deal with character encoding. Some parts are discussed here:
http://www.whitesmith.co/blog/latin1-to-utf8/
http://makandracards.com/makandra/571-mysql-server-and-utf-8-defaults
http://makandracards.com/makandra/595-dumping-and-importing-from-to-mysql-in-an-utf-8-safe-way

I will need some more time to figure this out in a way that works for (almost) all users. This may end up in using two different import sql files (so users just use the one that works) or requiring certain mysql settings to be made before installing the database. None of those is really great, but may be necessary.

So bear with me.

**Comment by bgreiner** [comment]
Hi,

I found the problem, and I found a solution. But it's complicated.

The problem is that in older PHP versions (< 5.3.6) the default MySQL connection character set in PHP is latin1. The setting to change that to UTF8 for versions <5.3.6 during the database initialization was applied at the wrong place, so there is a bug. (And I have a fix.)

The ORSEE database itself contains UTF8 characters, but they are encoded into latin1. (These are the scrambled characters.) When ORSEE makes a connection with an old PHP version, the connection is made in latin1 (due to the bug), the data is read in correctly, but is then interpreted as UTF8 for display, and so everything displays just fine.

For PHP versions >= 5.3.6, the database connection character set is correctly set to UTF8. The umlauts etc. are now read as genuine UTF8 (and not as latin1-encoded UTF8), so when they are displayed verbatim they appear scrambled.

What Max proposed is to properly encode the umlauts as genuine UTF8 in the database. After the database is properly converted, for newer PHP versions this fixes the display problem, because genuine UTF8 characters can now be directly displayed as UTF8. For older PHP versions, the bug fix needs to be applied such that the connection correctly uses UTF8, and then they also display the genuine UTF8 transferred via a UTF8 MySQL connection as UTF8.

However, there will be a problem for users of the older database version (used in all ORSEE versions until the current one). When they apply the bugfix, then the latin1-encoded UTF8 characters will be displayed wrongly, the same way as is currently the case for Max and other users of newer PHP versions. The question is how to deal with these older database versions. Any idea?

Cheers

/ben

**Comment by bgreiner** [comment]
Hi Max,

Could you do me a favor and check whether everything works alright with 
the attached install.sql?

Thanks

/ben

**Comment by kabalin** [comment]
@bgreiner nothing seems got attached... try attaching it using web-interface for commenting.

**Comment by bgreiner** [comment]
They do not allow .zip or .sql files, so I had to rename to .txt. Here is the install.sql in UTF8:

[install_utf.sql.txt](https://github.com/orsee/orsee/files/8872/install_utf.sql.txt)

**Comment by bgreiner** [comment]
I proposed a solution (including database upgrade for affected users) here:
https://github.com/bgreiner/orsee/commit/ea8d61cdd05982c69d509bfe8a24b91f704e3e22

**Comment by kabalin** [comment]
@bgreiner I have just tested your patch, both for existing installation with wrong characters (run convert script) and also tested doing new installation using updated install.sql. In both cases the proposed change works fine for me (I am on Debian Jessie). Feel free to submit a pull request.

I think INSTALL.howto needs to be updated as well, to make sure that newly created database has correct default settings, database creation line should be:
```mysql> CREATE DATABASE orseedbname DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;```

I am not sure what should be the procedure when someone is upgrading from 2.0.2 to 3.0.3, do they need to run importing script and then conversion script, this probably require to be documented.

**Comment by bgreiner** [comment]
Thanks! That's very helpful.

Yes, I also had thought about the two issues you mention. Will update 
INSTALL.howto, and will run a test with an older 2.2 database to see how 
that works.

/ben

**Comment by kabalin** [comment]
@bgreiner Just tested running data_import.php (after applying your patch) from 2.0.2 to clean installation of 3.0.3, works perfectly, no need to run conversion afterwards.

One thing I had to run on 2.0.2 database prior to import was this script http://stackoverflow.com/a/24391682/447249, but purely to avoid collation error which I had previosuly in 3.0.0 migration as well (something about particular setup of Mysql I dumped file from, since noone reported it, I think this is just particular setup issue, so it probably can be ignored).

**Comment by kabalin** [comment]
Hmm, since default email and general lang items are not imported, then my conclusion in previous comment might be wrong...

**Comment by bgreiner** [comment]
@kabalin I also tested data_import.php with an upgrade from 2.2.3 to 3.0.2, with participant names that contained umlauts. They appear scrambled after import. But running convert_orsee302db_to_UTF8.php fixes the issue.

So I'll update the instructions that after a data import the user might need to run convert_orsee302db_to_UTF8.php.

**Comment by bgreiner** [comment]
@kabalin Well, actually, convert_orsee302db_to_UTF8.php correctly converts the umlauts in the participant data, but scrambles all the correctly UTF8-encoded umlauts from the original install.sql. So there is a mess. I will need to find some way to detect whether a field is correctly or wrongly encoded. I can detect whether there are UTF8-characters in a text - will see whether that helps.

**Comment by bgreiner** [comment]
@kabalin I fixed this now, I think. convert_orsee302db_to_UTF8.php will now check, for each line read via the latin1 connection from the database, whether this line contains any valid UTF8 characters. Only if that's so, it will write back the data via the UTF8 connection.
This will protect correctly encoded UTF8 data from conversion, because such data red through a latin1 connection does not look like UTF8. It will also ignore any fields that do not contain any UTF8 (in whatever encoding) at all.

**Comment by kabalin** [comment]
Thanks @bgreiner! I can test your updated convert_orsee302db_to_UTF8.php in the evening if you post it on your fork.

**Comment by bgreiner** [comment]
I will submit it as a pull request, together with two other fixes. If tested and ok, I think we should publish as orsee 3.0.3.

**Comment by bgreiner** [comment]
This is now sorted out in Pull Request 12 https://github.com/orsee/orsee/pull/12

**Pull request closed without merging**
