### PR TITLE
Bugfixes for 3.0.2

### PR DESCRIPTION
**Pull request by bgreiner**
This pull request contains three fixes.

The first replaces install.sql and a truly UTF8-encoded file, provides a conversion tool and also updates some other related files.

The second fixes a javascript bug that seems only to pop up with Firefox.

The third deletes two functions that are not used in ORSEE.

### CODE REVIEW

**Comment by kabalin** [comment]
Hello @bgreiner, thanks for pull request. The code looks good to me, I have left few minor inline comments all indents related.

**Comment by bgreiner** [comment]
Ok, I updated according to your comments (except for the last one on query format: this is how multi-line queries are formatted basically anywhere in ORSEE).

**Comment by kabalin** [comment]
OK, looks good to me. I will test conversion once again later today and then merge.

**Comment by kabalin** [comment]
Tested on fresh installation using latest release sql file, conversion works fine for me. Thanks @bgreiner  for fixing umlauts issue.

**Pull request merged**
