### PR TITLE
Fix wrong encoding of umlauts

### PR DESCRIPTION
**Pull request by MaxG87**
Hi there,
since there is now a way to contribute to ORSEE, I decided to fix the umlaut encoding myself and create a pull request.

What I did is to issue some sed commands. Please have a look at the commit message.

sincerely,
Max

### CODE REVIEW

**Comment by kabalin** [comment]
Hello @MaxG87, thanks for the commit. It seems your pull request is based on master, please re-apply your change to develop branch and update the pull request. We do not merge changes made directly on master, it brings master commits to develop branch which is against current branching policy. We will release detailed documentation for code contributors soon.

**Comment by kabalin** [comment]
@MaxG87, well there is a way not to close pull requests if you just need to update the code, basically you just need to amend branch locally and force push it to your fork, this will automatically update pull request created from the branch. @bgreiner we might need to document this for contributors in the wiki.

**Comment by MaxG87** [comment]
Hi,
I'm sorry but I'm very new to use git in a collaborative way. I already had a hard time giving you just one commit and not all what I changed.

I opened another pull request and try to do better next time.

**Comment by kabalin** [comment]
@MaxG87 Enjoy Git! The more you do, the more you learn ;) Feel free to ask questions if you need some help.

**Pull request closed without merging**
