### PR TITLE
Bugfixes 3.0.1

### PR DESCRIPTION
**Pull request by bgreiner**
This is a series of bugfixes for orsee-3.0.0. After application, we should publish orsee-3.0.1.

### CODE REVIEW

**Comment by kabalin** [comment]
Ben, thanks for pull request. Really good work! I have left some minor in-line comments for you to address. Feel free to resubmit pull request when done. Notice, there is no need to close it and submit new, there is a way to make force push (git push origin/bugfixes-3.0.1 --force), this will override the branch with new changes you made to address the issue (if you end up modifying commits in the past prior to pushing).

**Comment by kabalin** [comment]
Ben, this will be useful for you to learn (if you have not done so already), how to modify commit in the past of commits history (e.g. when review outcomes require to change something in the middle of your commits history like in this pull request scenario): https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History Notice, that this method (git rebase -i) is only safe to use on local commits that where not pushed anywhere or your personal fork branches only. Never use it on public (upstream) - interactive rebasing is modifying commit hashes, people who checked out branch before something changed in the past will likely need to delete it and checkout again (which would require more work if they developed something on top of it already), there will be no way to fast-forward for them, very bad practice.

**Comment by bgreiner** [comment]
Mmmh, it seems that one problem with the git push origin bugfixes-3.0.1 --force is that now the comments on the previous commits are lost.

Anyway: I applied all changes you suggested.

**Comment by kabalin** [comment]
Well, comments are lost because the code lines they were referring to have changed. I think it is reasonable and helps to avoid confusion. Comments left here outside the code are not lost. I will have another look through now.

**Comment by kabalin** [comment]
Looks good to me, Ben! Thanks for making amendments. OK, I merge it then.

**Pull request merged**
